<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-UN2ELBQ" name="Chrome Test" tests="19" failures="10" timestamp="2 Jun 2019 20:17:06 GMT" time="88.768" errors="0">
  <testcase name="testCase2" time="0.009" classname="Framework.TestNG.TestNGBasics"/>
  <testcase name="infinitFailure" time="0.001" classname="Framework.TestNG.LoginTest"/>
  <testcase name="shoppingCartTest" time="2.312" classname="Framework.TestNG.Practice1"/>
  <testcase name="addToShoppingCartItem1" time="8.807" classname="Framework.TestNG.Practice2"/>
  <testcase name="testLogIn" time="3.215" classname="Framework.TestNG.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [My account] but found [My Account]">
      <![CDATA[java.lang.AssertionError: expected [My account] but found [My Account]
	at Framework.TestNG.LoginTest.testLogIn(LoginTest.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testLogIn -->
  <testcase name="loginWithCorrectPasswordAndUser" time="2.966" classname="Framework.TestNG.Practice1"/>
  <testcase name="testLogIn" time="3.029" classname="Framework.TestNG.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [My account] but found [My Account]">
      <![CDATA[java.lang.AssertionError: expected [My account] but found [My Account]
	at Framework.TestNG.LoginTest.testLogIn(LoginTest.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testLogIn -->
  <testcase name="loginWithIncUser" time="2.893" classname="Framework.TestNG.Practice1"/>
  <testcase name="testLogIn" time="3.311" classname="Framework.TestNG.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [My account] but found [My Account]">
      <![CDATA[java.lang.AssertionError: expected [My account] but found [My Account]
	at Framework.TestNG.LoginTest.testLogIn(LoginTest.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testLogIn -->
  <testcase name="loginWithIncPassword" time="3.039" classname="Framework.TestNG.Practice1"/>
  <testcase name="testLogIn" time="3.524" classname="Framework.TestNG.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [My account] but found [My Account]">
      <![CDATA[java.lang.AssertionError: expected [My account] but found [My Account]
	at Framework.TestNG.LoginTest.testLogIn(LoginTest.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testLogIn -->
  <testcase name="loginWithIncPasswordAndUser" time="3.241" classname="Framework.TestNG.Practice1"/>
  <testcase name="testLogIn" time="3.31" classname="Framework.TestNG.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [My account] but found [My Account]">
      <![CDATA[java.lang.AssertionError: expected [My account] but found [My Account]
	at Framework.TestNG.LoginTest.testLogIn(LoginTest.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testLogIn -->
  <testcase name="testLogIn" time="2.831" classname="Framework.TestNG.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [My account] but found [My Account]">
      <![CDATA[java.lang.AssertionError: expected [My account] but found [My Account]
	at Framework.TestNG.LoginTest.testLogIn(LoginTest.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testLogIn -->
  <testcase name="testLogIn" time="2.753" classname="Framework.TestNG.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [My account] but found [My Account]">
      <![CDATA[java.lang.AssertionError: expected [My account] but found [My Account]
	at Framework.TestNG.LoginTest.testLogIn(LoginTest.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testLogIn -->
  <testcase name="testLogIn" time="3.265" classname="Framework.TestNG.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [My account] but found [My Account]">
      <![CDATA[java.lang.AssertionError: expected [My account] but found [My Account]
	at Framework.TestNG.LoginTest.testLogIn(LoginTest.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testLogIn -->
  <testcase name="testLogIn" time="2.886" classname="Framework.TestNG.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [My account] but found [My Account]">
      <![CDATA[java.lang.AssertionError: expected [My account] but found [My Account]
	at Framework.TestNG.LoginTest.testLogIn(LoginTest.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testLogIn -->
  <testcase name="testLogIn" time="2.889" classname="Framework.TestNG.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [My account] but found [My Account]">
      <![CDATA[java.lang.AssertionError: expected [My account] but found [My Account]
	at Framework.TestNG.LoginTest.testLogIn(LoginTest.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testLogIn -->
  <testcase name="testLogIn2" time="2.856" classname="Framework.TestNG.LoginTest"/>
</testsuite> <!-- Chrome Test -->
